steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-east1-docker.pkg.dev/bicheka-396702/bicheka-repo/bicheka-396702/bicheka-frontend', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-east1-docker.pkg.dev/bicheka-396702/bicheka-repo/bicheka-396702/bicheka-frontend']