apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
spec:
  replicas: 3 # Adjust as needed
  selector:
    matchLabels:
      app: gke-test
  template:
    metadata:
      labels:
        app: gke-test
    spec:
      containers:
        - name: frontend
          image: gcr.io/bicheka-396702/bicheka-repo/frontend:latest # Replace with your image reference
          ports:
            - containerPort: 3000
