apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

images:
  - name: gcr.io/your-project-id/your-react-app
    newName: us-central1-docker.pkg.dev/your-project-id/your-repo-name/your-react-app
    newTag: latest
