apiVersion: v1
kind: Service
metadata:
  name: gke-test-service
spec:
  selector:
    app: gke-test
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer # Use LoadBalancer type for external access on GKE